format = """\
$username[@](yellow bold)$hostname 🧉 em $directory\
$git_branch\
$package\
$cmd_duration
$character\
"""

add_newline = false

[username]
show_always = true
format = "[$user]($style)"
style_user = "bold green dimmed"
style_root = "green bold"

[hostname]
ssh_only = false
format = "[$hostname]($style)"
style = "blue dimmed bold"

[directory]
format = "[$path]($style)"
truncate_to_repo = false

[git_branch]
format = "[ em \\[$symbol $branch\\]]($style)"
symbol = "👻"

[cmd_duration]
min_time = 1_000
format = "[ \\(levou $duration\\) ]($style)"

[character]
success_symbol = "[ 🤘 ~> ](bold fg:#000000 bg:purple)"
error_symbol = "[ 🤘 ~> ](bold fg:#000000 bg:purple)"
